export const ADD_TO_DONATION = 'ADD_TO_DONATION';
export const REMOVE_FROM_DONATION = 'REMOVE_FROM_DONATION';
export const UPDATE_DONATION_QUANTITY = 'UPDATE_DONATION_QUANTITY';
export const CLEAR_DONATION = 'CLEAR_DONATION';
export const TOGGLE_DONATION = 'TOGGLE_DONATION';